services:
  - type: web
    plan: free
    name: sijarta
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn sijarta.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        value: postgresql://postgresql:HOlJuL6NucqWnOkw@aws-0-ap-southeast-1.pooler.supabase.com:6543/postgres
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4