# Generated by Django 4.2.4 on 2024-11-07 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id_fasilitas', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nama_fasilitas', models.CharField(max_length=100)),
                ('deskripsi', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id_tamu', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('alamat', models.TextField()),
                ('no_telp', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('tipe', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('kapasitas', models.IntegerField()),
                ('harga_per_malam', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('no_kamar', models.IntegerField(primary_key=True, serialize=False)),
                ('ketersediaan', models.BooleanField(default=True)),
                ('tipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyPay.roomtype')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id_reservasi', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('tanggal_check_in', models.DateField()),
                ('tanggal_check_out', models.DateField()),
                ('status', models.CharField(choices=[('diproses', 'Diproses'), ('selesai', 'Selesai'), ('batal', 'Batal')], max_length=20)),
                ('id_tamu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyPay.guest')),
                ('no_kamar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyPay.room')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id_pembayaran', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('biaya', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metode', models.CharField(choices=[('transfer_bank', 'Transfer Bank'), ('kredit', 'Kredit')], max_length=20)),
                ('id_reservasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyPay.reservation')),
            ],
        ),
        migrations.CreateModel(
            name='FacilityBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_fasilitas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyPay.facility')),
                ('id_reservasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyPay.reservation')),
            ],
        ),
    ]
