# Generated by Django 4.2.4 on 2024-11-18 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_pekerja_unique_together_remove_pengguna_npwp_and_more'),
        ('MyPay', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pengguna')),
            ],
        ),
        migrations.CreateModel(
            name='MyPayTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('mypay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='MyPay.mypay')),
            ],
        ),
        migrations.RemoveField(
            model_name='facilitybooking',
            name='id_fasilitas',
        ),
        migrations.RemoveField(
            model_name='facilitybooking',
            name='id_reservasi',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='id_reservasi',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='id_tamu',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='no_kamar',
        ),
        migrations.RemoveField(
            model_name='room',
            name='tipe',
        ),
        migrations.DeleteModel(
            name='Facility',
        ),
        migrations.DeleteModel(
            name='FacilityBooking',
        ),
        migrations.DeleteModel(
            name='Guest',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='RoomType',
        ),
    ]
