# Generated by Django 4.2.7 on 2024-11-17 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pengguna',
            options={'verbose_name': 'Pengguna', 'verbose_name_plural': 'Pengguna'},
        ),
        migrations.RemoveField(
            model_name='pengguna',
            name='pwd',
        ),
        migrations.AddField(
            model_name='pengguna',
            name='npwp',
            field=models.CharField(default='000000000000000', max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='pengguna',
            name='jenis_kelamin',
            field=models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1),
        ),
        migrations.AlterField(
            model_name='pengguna',
            name='no_hp',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='pengguna',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pengguna', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Pekerja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('jenis_kelamin', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1)),
                ('no_hp', models.CharField(max_length=20, unique=True)),
                ('tgl_lahir', models.DateField()),
                ('alamat', models.CharField(max_length=255)),
                ('nama_bank', models.CharField(choices=[('GoPay', 'GoPay'), ('OVO', 'OVO'), ('VA BCA', 'Virtual Account BCA'), ('VA BNI', 'Virtual Account BNI'), ('VA Mandiri', 'Virtual Account Mandiri')], max_length=50)),
                ('no_rekening', models.CharField(max_length=20)),
                ('npwp', models.CharField(default='000000000000000', max_length=15, unique=True)),
                ('foto_url', models.URLField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pekerja', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pekerja',
                'verbose_name_plural': 'Pekerja',
                'unique_together': {('nama_bank', 'no_rekening')},
            },
        ),
    ]
