# Generated by Django 4.2.7 on 2024-11-18 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_pengguna_options_remove_pengguna_pwd_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KategoriJasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kategori', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Kategori Jasa',
                'verbose_name_plural': 'Kategori Jasa',
            },
        ),
        migrations.CreateModel(
            name='SubkategoriJasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_subkategori', models.CharField(max_length=255, unique=True)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subkategori', to='main.kategorijasa')),
            ],
            options={
                'verbose_name': 'Subkategori Jasa',
                'verbose_name_plural': 'Subkategori Jasa',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('pekerja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='main.pekerja')),
                ('pengguna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='main.pengguna')),
            ],
        ),
    ]
