# Generated by Django 5.1.3 on 2024-11-18 08:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_kategorijasa_subkategorijasa_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pekerja',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='pengguna',
            name='npwp',
        ),
        migrations.AddField(
            model_name='pekerja',
            name='jumlah_pesanan_selesai',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pekerja',
            name='kategori_pekerjaan',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pekerja', to='main.kategorijasa'),
        ),
        migrations.AddField(
            model_name='pekerja',
            name='pwd',
            field=models.CharField(default='default_password', max_length=255),
        ),
        migrations.AddField(
            model_name='pekerja',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='pekerja',
            name='saldomypay',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pengguna',
            name='level',
            field=models.CharField(default='basic', max_length=50),
        ),
        migrations.AddField(
            model_name='pengguna',
            name='pwd',
            field=models.CharField(default='default_password', max_length=255),
        ),
        migrations.AddField(
            model_name='pengguna',
            name='saldomypay',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pekerja',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pekerja',
            name='no_rekening',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='pekerja',
            name='npwp',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='pekerja',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pengguna',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pengguna',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
