# Generated by Django 5.1.3 on 2024-12-05 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_pekerja_unique_together_remove_pengguna_npwp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pekerja',
            name='kategori_pekerjaan',
        ),
        migrations.RemoveField(
            model_name='subkategorijasa',
            name='kategori',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pekerja',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pengguna',
        ),
        migrations.RemoveField(
            model_name='pekerja',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pengguna',
            name='user',
        ),
        migrations.DeleteModel(
            name='KategoriJasa',
        ),
        migrations.DeleteModel(
            name='SubkategoriJasa',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Pekerja',
        ),
        migrations.DeleteModel(
            name='Pengguna',
        ),
    ]
