# Generated by Django 4.2.4 on 2024-11-07 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PekerjaanJasa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobStatus',
            fields=[
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='PekerjaanJasa.job')),
                ('status', models.CharField(choices=[('menunggu', 'Menunggu Pekerja Berangkat'), ('tiba', 'Pekerja Tiba di Lokasi'), ('dilakukan', 'Pelayanan Jasa Sedang Dilakukan'), ('selesai', 'Pesanan Selesai'), ('dibatalkan', 'Pesanan Dibatalkan')], max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
